### ISSUE TITLE
two spec failures with rails 6.0.3

### ISSUE THREAD

**Issue by boutil** [ilyakatz/data-migrate#155]
Hello,

when trying to run the specs with rails 6.0.3 and ruby2.7.2 (Debian unstable), I get the following failures:
```
Failures:

  1) DataMigrate::DatabaseTasks migrations load_schema_current loads the current schema file
     Failure/Error: subject.load_schema_current
     
     ActiveRecord::AdapterNotSpecified:
       The `development` database is not configured for the `development` environment.
     
       Available databases configurations are:
     
       test: primary, primary, primary, primary
     # /usr/share/rubygems-integration/all/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/connection_specification.rb:250:in `resolve_symbol_connection'
     # /usr/share/rubygems-integration/all/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/connection_specification.rb:218:in `resolve_connection'
     # /usr/share/rubygems-integration/all/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
     # /usr/share/rubygems-integration/all/gems/activerecord-6.0.3.4/lib/active_record/connection_handling.rb:170:in `resolve_config_for_connection'
     # /usr/share/rubygems-integration/all/gems/activerecord-6.0.3.4/lib/active_record/connection_handling.rb:50:in `establish_connection'
     # /usr/share/rubygems-integration/all/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:427:in `load_schema_current'
     # ./spec/data_migrate/database_tasks_spec.rb:101:in `block (4 levels) in <top (required)>'

  2) DataMigrate::DatabaseTasks migrations load_schema_current loads schema file that has not been update with latest data migrations
     Failure/Error: subject.load_schema_current
     
     ActiveRecord::AdapterNotSpecified:
       The `development` database is not configured for the `development` environment.
     
       Available databases configurations are:
     
       test: primary, primary, primary, primary, primary
     # /usr/share/rubygems-integration/all/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/connection_specification.rb:250:in `resolve_symbol_connection'
     # /usr/share/rubygems-integration/all/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/connection_specification.rb:218:in `resolve_connection'
     # /usr/share/rubygems-integration/all/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
     # /usr/share/rubygems-integration/all/gems/activerecord-6.0.3.4/lib/active_record/connection_handling.rb:170:in `resolve_config_for_connection'
     # /usr/share/rubygems-integration/all/gems/activerecord-6.0.3.4/lib/active_record/connection_handling.rb:50:in `establish_connection'
     # /usr/share/rubygems-integration/all/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:427:in `load_schema_current'
     # ./spec/data_migrate/database_tasks_spec.rb:113:in `block (4 levels) in <top (required)>'

Finished in 2.36 seconds (files took 1.97 seconds to load)
47 examples, 2 failures
```

Is there any prior action required before running rspec in order to ensure it passes?
